# Copyright (c) 2017 Amazon.com, Inc. or its affiliates.  All Rights
#                    reserved.
#
# Copyright (c) 2017      Intel, Inc. All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

PROGS = reachable_weighted reachable_netlink

all: $(PROGS)

CC = ortecc
CFLAGS = -g

clean:
	rm -f $(PROGS) *~
