# Use "required" for sudo, because we want to use the "trusty" Debian
# distro, which is (currently) only available in the legacy Travis
# infrastructure (i.e., if we put "sudo: false" to use the new container-
# based Travis infrastructure, then "trusty" is not available).  We
# need the "trusty" distro because it has more recent versions of the
# GNU Autotools (i.e., autogen.pl will fail if you use the regular
# distro because the GNU Autotools are too old).
sudo: required
dist: trusty
language: c

# Iterate over 2 different compilers
compiler:
    - gcc

# Test only linux now
os:
    - linux

addons:
    # For Linux, make sure we have some extra packages that we like to
    # build with
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - libnl-3-200
            - libnl-3-dev
            - libnl-route-3-200
            - libnl-route-3-dev
            - libibverbs-dev
            - librdmacm-dev
            - libhwloc-dev
            - libevent-dev
            - cython
        sources:
            - ubuntu-toolchain-r-test

env:
    global:
        - AM_MAKEFLAGS="-j4"
        - CPPFLAGS="-I$HOME/bogus/include"
        - LDFLAGS="-L$HOME/bogus/lib"
        - LD_LIBRARY_PATH="$HOME/bogus/lib"

before_install:
    - export CONFIGURE_ARGS="--prefix=$HOME/bogus --enable-orterun-prefix-by-default $COMPILERS" DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_ARGS"
    - export DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_ARGS"
    - ./contrib/travis/install-pmix.sh


# Note that we use "make -k" to do the entire build, even if there was a
# build error in there somewhere.  This prevents us from needing to submit
# to Travis, see the first error, fix that first error, submit again, ...etc.
install:
    - m4 --version
    - autoconf --version
    - automake --version
    - libtool --version
    - ./autogen.pl
    - ./configure $CONFIGURE_ARGS
    - make -k
    - make install

script:
    - make check
    - ./contrib/travis/test_client.sh
