#
# Copyright (c) 2026      Sandia National Laboratories  All rights reserved.
# Copyright (c) 2026      Nanook Consulting  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

headers += \
      rml/relm/relm.h \
      rml/relm/state_machine.h \
      rml/relm/types.h \
      rml/relm/util.h

libprrte_la_SOURCES += \
      rml/relm/relm.c \
      rml/relm/state_machine.c \
      rml/relm/state_updates.c \
      rml/relm/link_updates.c \
      rml/relm/types.c \
      rml/relm/util.c
