.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "prte_filem" "7" "" "2021-08-23" "PRRTE"
.hy
.SH NAME
.PP
PRTE_FILEM - PRTE MCA File Management (FileM) Framework: Overview of
PRTE\[cq]s FileM framework, and selected modules.
.SH DESCRIPTION
.PP
FileM is a utility framework used by PRTE for a variety of purposes,
including the transport of checkpoint files, preloading user binaries,
and preloading of user files.
.SH AVAILABLE COMPONENTS
.PP
PRTE currently ships with one FileM component: \f[C]rsh\f[R].
.PP
The following MCA parameters apply to all components:
.TP
\f[B]\f[CB]filem_base_verbose\f[B]\f[R]
Set the verbosity level for all components.
Default is 0, or silent except on error.
.SS rsh FileM Component
.PP
The \f[C]rsh\f[R] component uses \f[C]rcp\f[R] or \f[C]scp\f[R] to do
its file transfers.
This component requires the use of passwordless \f[C]rsh\f[R] or
\f[C]ssh\f[R] between all nodes.
.PP
The \f[C]rsh\f[R] component has the following MCA parameters:
.TP
\f[B]\f[CB]filem_rsh_priority\f[B]\f[R]
The component\[cq]s priority to use when selecting the most appropriate
component for a run.
.TP
\f[B]\f[CB]filem_rsh_verbose\f[B]\f[R]
Set the verbosity level for this component.
Default is 0, or silent except on error.
.TP
\f[B]\f[CB]filem_rsh_rcp\f[B]\f[R]
The program to use to copy files.
Generally will be \f[C]rcp\f[R] or \f[C]scp\f[R].
.TP
\f[B]\f[CB]filem_rsh_rsh\f[B]\f[R]
The program used to remotely log into a given machine and remove files.
Generally will be \f[C]rsh\f[R] or \f[C]ssh\f[R].
.SS none FileM Component
.PP
The \f[C]none\f[R] component simply selects no FileM component.
All of the FileM function calls return immediately with PRTE_SUCCESS.
.PP
This component is the last component to be selected by default.
This means that if another component is available, and the
\f[C]none\f[R] component was not explicity requested then PRTE will
attempt to activate all of the available components before falling back
to this component.
.SH SEE ALSO
.PP
prte-checkpoint(1), prte-restart(1), prte-checkpoint(1),
prte-restart(1), prte_snapc(7), prte_crs(7)
