#!/bin/bash
#
# Copyright (c) 2026      Nanook Consulting  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#
# scaletest.sh -- measure how the DVM collectives scale.
#
# This is a MEASUREMENT harness, not a pass/fail suite.  run-tests.sh answers
# "is it correct"; this answers "what does it cost", and it writes a CSV that
# drops straight into a spreadsheet.
#
# It stands up its own swarm (default: 40 containers under PRTE_SWARM=scale)
# so it never disturbs the ten-node functional swarm, and it sweeps four
# independent knobs:
#
#     --nodes    how many containers are in the DVM
#     --ppn      how many application procs run on each of them
#     --radix    the routing radix, i.e. the shape of the daemon tree
#     --nkeys / --sizes    how much data each rank contributes
#
# For every combination it runs the scaletest client, which times a full-data
# PMIx_Fence (PMIX_COLLECT_DATA true -- the allgather) and a bare barrier
# (PMIX_COLLECT_DATA false) over the whole job.  See scaletest.c for what
# each phase is and why the timestamps are absolute.
#
# Usage:
#     ./scaletest.sh up [N]        generate the compose file and start N nodes
#     ./scaletest.sh down          stop and remove them
#     ./scaletest.sh build         build PRRTE+PMIx into this swarm volume
#     ./scaletest.sh run [opts]    run the sweep
#     ./scaletest.sh clean         sweep stale daemons/session dirs
#
# Typical first run, from this directory:
#
#     ./scaletest.sh build         # PMIX_SRC=<openpmix checkout> to build PMIx too
#     ./scaletest.sh up 40
#     ./scaletest.sh run --nodes 1,2,4,8,16,32,40 --ppn 1,2 --radix 2,4,64
#
# The radix is a property of the DVM, fixed when the daemons start, so the
# sweep restarts the DVM for every (nodes, radix) pair and runs the cheaper
# knobs -- ppn, nkeys, sizes -- inside that.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# A swarm of this harness own, kept apart from the functional one.  Same
# derivation build.sh and docker-compose.yml use, so PRTE_SWARM works the
# usual way if you want a different name.
PRTE_SWARM="${PRTE_SWARM:-scale}"
NODE="${PRTE_SWARM}-node"
PROJECT="${PRTE_SWARM}swarm"
VOLUME="${PRTE_SWARM}-build"
IMAGE="${IMAGE:-prte-swarm:latest}"
COMPOSE="$here/docker-compose.$PRTE_SWARM.yml"

# How many containers the swarm has.  Recorded when "up" generates the
# compose file so "run" can refuse a --nodes larger than the swarm.
SWARM_NODES_DEFAULT=40

URI=/tmp/scale-dvm.uri
BIN=/opt/prte/prte/bin/scaletest       # absolute: see AGENTS.md section 14

DOCKER_ENV=(-e PRTE_ALLOW_RUN_AS_ROOT=1 -e PRTE_ALLOW_RUN_AS_ROOT_CONFIRM=1)

RUN() { docker exec "${DOCKER_ENV[@]}" "${NODE}1" bash -lc ". /opt/prte/env.sh; $*"; }

die() { echo "ERROR: $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# swarm lifecycle
# ---------------------------------------------------------------------------

# docker compose cannot loop, so the service blocks are generated.  Everything
# else about the file matches docker-compose.yml: same image, same read-only
# mount of the shared build volume, project name pinned so a stray `docker
# compose` in this directory cannot adopt another project.
gen_compose() {
    local n=$1 i

    {
        printf '# GENERATED by scaletest.sh -- do not edit; regenerate with\n'
        printf '#     ./scaletest.sh up %s\n#\n' "$n"
        printf '# A %s-container swarm for collective scaling measurement.  It is separate\n' "$n"
        printf '# from the functional swarm in docker-compose.yml so a sweep cannot disturb\n'
        printf '# run-tests.sh, and vice versa.\n'
        printf 'name: %s\n\n' "$PROJECT"
        printf 'x-node: &node\n'
        printf '  image: %s\n' "$IMAGE"
        printf '  networks: [dvm]\n'
        printf '  tty: true\n'
        printf '  volumes:\n'
        printf '    - prte-build:/opt/prte:ro\n\n'
        printf 'services:\n'
        for ((i = 1; i <= n; i++)); do
            printf '  node%s:\n    <<: *node\n    hostname: node%s\n    container_name: %s%s\n' \
                   "$i" "$i" "$NODE" "$i"
        done
        printf '\nnetworks:\n  dvm:\n    driver: bridge\n'
        printf '\nvolumes:\n  prte-build:\n    name: %s\n    external: true\n' "$VOLUME"
    } > "$COMPOSE"
    echo "$n" > "$here/.${PRTE_SWARM}-nodecount"
}

swarm_size() {
    if [ -f "$here/.${PRTE_SWARM}-nodecount" ]; then
        cat "$here/.${PRTE_SWARM}-nodecount"
    else
        echo 0
    fi
}

cmd_up() {
    local n=${1:-$SWARM_NODES_DEFAULT}

    docker image inspect "$IMAGE" >/dev/null 2>&1 || \
        die "image $IMAGE does not exist -- run ./build.sh image first"
    docker volume inspect "$VOLUME" >/dev/null 2>&1 || \
        die "volume $VOLUME does not exist -- run ./scaletest.sh build first"

    gen_compose "$n"
    echo ">>> starting $n nodes (project $PROJECT)"
    docker compose -f "$COMPOSE" up -d
    # The entrypoint symlinks the install bin and runs ldconfig at container
    # start; give it a moment before anything tries to launch a daemon.
    sleep 3
    echo ">>> $(docker compose -f "$COMPOSE" ps -q | wc -l | tr -d ' ') of $n containers running"
}

cmd_down() {
    [ -f "$COMPOSE" ] || die "no $COMPOSE -- nothing to take down"
    docker compose -f "$COMPOSE" down
}

cmd_build() {
    # build.sh derives the volume from PRTE_SWARM, so this puts the build in
    # THIS swarm volume and leaves the functional one alone.
    PRTE_SWARM="$PRTE_SWARM" "$here/build.sh" "$@"
}

# The same sweep cleanup_swarm does in run-tests.sh, over this swarm size.
# Every tool has its own session-dir prefix and one missed prefix is enough to
# make the next tool report "multiple possible servers" and fail to find the
# DVM.
cmd_clean() {
    local n i
    n=$(swarm_size)
    [ "$n" -gt 0 ] || die "swarm size unknown -- run ./scaletest.sh up first"
    for ((i = 1; i <= n; i++)); do
        docker exec "${NODE}$i" sh -c '
            for t in prted prte prterun prun pterm scaletest; do pkill -9 -x $t; done
            rm -rf /tmp/prte.* /tmp/prted.* /tmp/prtrn.* /tmp/prun.* /tmp/ompi.* /tmp/pmix.*
            find /tmp -maxdepth 2 -name "pmix.*" -prune -exec rm -rf {} +
            true' >/dev/null 2>&1 || true
    done
}

preflight() {
    local n
    n=$(swarm_size)
    [ "$n" -gt 0 ] || die "swarm size unknown -- run ./scaletest.sh up first"
    docker ps --format '{{.Names}}' | grep -qx "${NODE}1" || \
        die "swarm $PRTE_SWARM is not running -- ./scaletest.sh up $n"
    # The install lives in a volume that outlives any one build, so a build
    # that died part-way leaves the PREVIOUS install standing and every number
    # below would describe code that was never built.
    docker exec "${NODE}1" test -s /opt/prte/.build-stamp || \
        die "no build stamp in volume $VOLUME -- ./scaletest.sh build"
    docker exec "${NODE}1" test -x "$BIN" || \
        die "$BIN missing -- rebuild with ./scaletest.sh build"
    echo ">>> build stamp: $(docker exec "${NODE}1" cat /opt/prte/.build-stamp | tr '\n' ' ')"
}

# ---------------------------------------------------------------------------
# the sweep
# ---------------------------------------------------------------------------

# Start a DVM of $1 nodes with $2 slots each at routing radix $3, and do not
# return until it is actually that size.  A DVM that came up short would
# silently make the run below a measurement of a smaller machine.
dvm_start() {
    local nodes=$1 slots=$2 radix=$3
    local hosts="" i seen tries

    for ((i = 1; i <= nodes; i++)); do
        hosts="${hosts:+$hosts,}node$i:$slots"
    done

    RUN "rm -f $URI" >/dev/null 2>&1 || true
    docker exec -d "${DOCKER_ENV[@]}" "${NODE}1" bash -lc \
        ". /opt/prte/env.sh; prte --daemonize --report-uri $URI \
             --prtemca rml_base_radix $radix ${SCALE_DVM_MCA:-} \
             --host $hosts > /tmp/scale-dvm.out 2>&1"

    for ((tries = 0; tries < 120; tries++)); do
        if RUN "test -s $URI" >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done
    RUN "test -s $URI" >/dev/null 2>&1 || { echo "    DVM never reported a URI" >&2; return 1; }

    # Every daemon has to be up, not just the master.  One proc per node and
    # count the distinct hostnames.
    seen=$(RUN "timeout -k 5 120 prun --dvm-uri file:$URI --map-by ppr:1:node -n $nodes hostname" \
               2>/dev/null | sort -u | grep -c '^node' || true)
    if [ "${seen:-0}" -ne "$nodes" ]; then
        echo "    DVM came up with $seen of $nodes nodes" >&2
        return 1
    fi
    # prun returning is not the same as every proc having been reaped on every
    # daemon, and at 40 nodes the tail of that teardown is long enough to
    # matter: the next job asks for the slots this one has not finished
    # releasing and is refused with "All nodes which are allocated for this
    # job are already filled" (PMIX_ERR_JOB_FAILED_TO_MAP).  The slot headroom
    # in dvm_start covers the common case; this covers the rest.
    sleep 3
    return 0
}

dvm_stop() {
    RUN "timeout -k 5 60 pterm --dvm-uri file:$URI" >/dev/null 2>&1 || true
    cmd_clean
}

# Turn one run's captured SCALE lines into CSV rows on stdout.
#
# The wall-clock column is the number that answers the question this harness
# exists for -- how long from the FIRST rank entering the collective to the
# LAST one leaving it -- and it is computable only because every container
# shares the host kernel clock.  The max-local column is what a real cluster
# would have to settle for, and is reported alongside so the two can be
# compared.
parse_run() {
    local prefix=$1 capture=$2

    # The labels are located by name rather than by column number.  PRRTE can
    # prefix forwarded output (--output tag, a rank label, a stray banner), and
    # a fixed offset would then silently read the wrong field and report
    # nonsense rather than failing.
    awk -v prefix="$prefix" '
        function record(p, it, s, e,   loc) {
            if (!((p SUBSEP it) in have)) {
                have[p, it] = 1
                mins[p, it] = s
                maxe[p, it] = e
                maxl[p, it] = e - s
                if (!(it in iters)) { iters[it] = 1; order[++ni] = it }
            } else {
                if (s < mins[p, it]) { mins[p, it] = s }
                if (e > maxe[p, it]) { maxe[p, it] = e }
                loc = e - s
                if (loc > maxl[p, it]) { maxl[p, it] = loc }
            }
        }
        {
            it = ""; put = 0; col = 0; bar = 0
            for (i = 1; i <= NF; i++) {
                if ($i == "ITER")    { it  = $(i + 1) }
                if ($i == "PUT")     { put = i }
                if ($i == "COLLECT") { col = i }
                if ($i == "BARRIER") { bar = i }
            }
            if ("" == it || 0 == put || 0 == col || 0 == bar) { next }
            record(1, it, $(put + 1), $(put + 2))
            record(2, it, $(col + 1), $(col + 2))
            record(3, it, $(bar + 1), $(bar + 2))
        }
        END {
            for (i = 1; i <= ni; i++) {
                it = order[i]
                printf "%s,%s", prefix, it
                for (p = 1; p <= 3; p++) {
                    printf ",%.1f,%.1f", (maxe[p, it] - mins[p, it]) / 1000.0, maxl[p, it] / 1000.0
                }
                printf "\n"
            }
        }
    ' "$capture" | sort -t, -k9,9n
}

cmd_run() {
    local nodes_list="1,2,4,8,16,32,40"
    local ppn_list="1,2"
    local radix_list="2,4,64"
    local nkeys_list="8"
    local sizes_list="1024"
    local iters=5 warmup=1
    local out="$here/scale-results.csv"
    local max_bytes=$((256 * 1024 * 1024))
    # ...and the one that actually binds here.  Every "node" of this swarm is
    # a container on ONE host, so the memory the collected data occupies is
    # per-daemon TIMES the node count -- 128 MB a daemon across 40 nodes is
    # 5 GB, which a laptop Docker VM does not have.  On a real cluster only
    # the per-daemon figure would matter.
    local max_total_bytes=$((2 * 1024 * 1024 * 1024))
    local scope=global
    local dry=0
    local swarm_n

    while [ $# -gt 0 ]; do
        case "$1" in
            --nodes)     nodes_list=$2; shift 2 ;;
            --ppn)       ppn_list=$2; shift 2 ;;
            --radix)     radix_list=$2; shift 2 ;;
            --nkeys)     nkeys_list=$2; shift 2 ;;
            --sizes)     sizes_list=$2; shift 2 ;;
            --iters)     iters=$2; shift 2 ;;
            --warmup)    warmup=$2; shift 2 ;;
            --scope)     scope=$2; shift 2 ;;
            --out)       out=$2; shift 2 ;;
            --max-bytes)       max_bytes=$2; shift 2 ;;
            --max-total-bytes) max_total_bytes=$2; shift 2 ;;
            --dry-run)   dry=1; shift ;;
            *) die "unknown option $1" ;;
        esac
    done

    preflight
    swarm_n=$(swarm_size)

    local raw="${out%.csv}-raw.csv"
    local hdr="nodes,radix,ppn,nprocs,nkeys,sizes,bytes_per_rank,collected_bytes"
    echo "$hdr,iter,put_wall_us,put_max_local_us,collect_wall_us,collect_max_local_us,barrier_wall_us,barrier_max_local_us" > "$raw"

    # The largest ppn in the sweep is what every DVM is given as slots, so the
    # node pool does not change between the runs inside one DVM.
    #
    # Plus one, deliberately.  Mapping is by ppr:N:node, so the spare slot is
    # never filled and cannot change what is measured -- but without it a job
    # whose ppn exactly equals the slot count is refused outright if the
    # PREVIOUS job on this DVM has not finished releasing its slots.  That is
    # not hypothetical: --ppn 1 over 40 nodes failed every single run that way
    # (PMIX_ERR_JOB_FAILED_TO_MAP), while a sweep that happened to include a
    # larger ppn was fine, which is exactly the kind of accident that makes
    # the failure look like it belongs to the node count.
    local slots=1 p
    for p in ${ppn_list//,/ }; do
        if [ "$p" -ge "$slots" ]; then
            slots=$((p + 1))
        fi
    done

    local nodes radix ppn nkeys sizes cs nprocs bytes_per_rank collected tag capture
    for nodes in ${nodes_list//,/ }; do
        if [ "$nodes" -gt "$swarm_n" ]; then
            echo ">>> skipping nodes=$nodes: the swarm only has $swarm_n containers" >&2
            continue
        fi
        for radix in ${radix_list//,/ }; do
            echo ">>> DVM: nodes=$nodes radix=$radix slots=$slots"
            if [ "$dry" -eq 0 ]; then
                cmd_clean
                if ! dvm_start "$nodes" "$slots" "$radix"; then
                    echo ">>> FAILED to start DVM nodes=$nodes radix=$radix -- skipping" >&2
                    cmd_clean
                    continue
                fi
            fi

            for ppn in ${ppn_list//,/ }; do
                nprocs=$((nodes * ppn))
                for nkeys in ${nkeys_list//,/ }; do
                    for sizes in ${sizes_list//,/ }; do
                        # A sweep element may itself be a list of sizes the
                        # keys cycle through, joined with + -- because the
                        # sweep list is already comma-separated, and because
                        # the CSV column cannot hold a comma either.  The
                        # client wants commas, the CSV keeps the plus form.
                        cs=${sizes//+/,}
                        bytes_per_rank=$(awk -v k="$nkeys" -v s="$cs" 'BEGIN{
                            n=split(s, a, ","); t=0
                            for (i = 0; i < k; i++) { t += a[(i % n) + 1] }
                            print t }')
                        # After a collect fence EVERY daemon holds EVERY rank
                        # data, and the iterations use distinct keys, so this
                        # is what each daemon ends up carrying.
                        collected=$((bytes_per_rank * nprocs * (iters + warmup)))
                        if [ "$collected" -gt "$max_bytes" ]; then
                            echo "    skip ppn=$ppn nkeys=$nkeys sizes=$cs: $collected bytes/daemon > --max-bytes $max_bytes" >&2
                            continue
                        fi
                        if [ $((collected * nodes)) -gt "$max_total_bytes" ]; then
                            echo "    skip ppn=$ppn nkeys=$nkeys sizes=$cs: $((collected * nodes)) bytes across $nodes daemons on one host > --max-total-bytes $max_total_bytes" >&2
                            continue
                        fi

                        tag="n${nodes}r${radix}p${ppn}k${nkeys}s${sizes}"
                        echo "    run $tag  nprocs=$nprocs bytes/rank=$bytes_per_rank collected/daemon=$collected"
                        if [ "$dry" -eq 1 ]; then
                            continue
                        fi

                        capture=$(mktemp "${TMPDIR:-/tmp}/scale-XXXXXX")
                        if ! RUN "timeout -k 10 600 prun --dvm-uri file:$URI \
                                    --map-by ppr:$ppn:node --bind-to none -n $nprocs \
                                    $BIN --tag $tag --nkeys $nkeys --sizes $cs \
                                         --iters $iters --warmup $warmup --scope $scope" \
                                 > "$capture" 2>&1; then
                            echo "    FAILED: $(tail -3 "$capture" | tr '\n' ' ')" >&2
                            rm -f "$capture"
                            continue
                        fi
                        if grep -q "FAILED" "$capture"; then
                            echo "    client error: $(grep -m1 FAILED "$capture")" >&2
                            rm -f "$capture"
                            continue
                        fi
                        parse_run "$nodes,$radix,$ppn,$nprocs,$nkeys,$sizes,$bytes_per_rank,$collected" \
                                  "$capture" >> "$raw"
                        rm -f "$capture"
                    done
                done
            done

            if [ "$dry" -eq 0 ]; then
                dvm_stop
            fi
        done
    done

    if [ "$dry" -eq 1 ]; then
        echo ">>> dry run: nothing was executed"
        return 0
    fi

    summarize "$raw" "$out"
    echo
    echo ">>> raw     (one row per iteration): $raw"
    echo ">>> summary (one row per config)   : $out"
    echo
    column -s, -t < "$out"
}

# Median over the iterations of each config, plus min and max, and the
# difference between the two fences -- which is what the payload itself cost.
summarize() {
    local raw=$1 out=$2

    awk -F, 'NR > 1 {
        key = $1 "," $2 "," $3 "," $4 "," $5 "," $6 "," $7 "," $8
        if (!(key in seen)) { seen[key] = 1; order[++nk] = key }
        # raw columns: 1-8 config, 9 iter, 10 put_wall, 11 put_max_local,
        # 12 collect_wall, 13 collect_max_local, 14 barrier_wall,
        # 15 barrier_max_local
        c[key, ++cn[key]] = $12
        b[key, ++bn[key]] = $14
        p[key, ++pn[key]] = $10
    }
    function med(arr, key, n,   v, i, j, t) {
        for (i = 1; i <= n; i++) { v[i] = arr[key, i] }
        for (i = 1; i < n; i++) { for (j = i + 1; j <= n; j++) {
            if (v[j] < v[i]) { t = v[i]; v[i] = v[j]; v[j] = t } } }
        return (n % 2) ? v[(n + 1) / 2] : (v[n / 2] + v[n / 2 + 1]) / 2.0
    }
    function mn(arr, key, n,   i, m) { m = arr[key, 1]
        for (i = 2; i <= n; i++) { if (arr[key, i] < m) { m = arr[key, i] } } return m }
    function mx(arr, key, n,   i, m) { m = arr[key, 1]
        for (i = 2; i <= n; i++) { if (arr[key, i] > m) { m = arr[key, i] } } return m }
    END {
        print "nodes,radix,ppn,nprocs,nkeys,sizes,bytes_per_rank,collected_bytes,samples," \
              "put_med_us,collect_med_us,collect_min_us,collect_max_us," \
              "barrier_med_us,barrier_min_us,barrier_max_us,data_cost_us"
        for (i = 1; i <= nk; i++) {
            key = order[i]; n = cn[key]
            cm = med(c, key, n); bm = med(b, key, n)
            printf "%s,%d,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f\n", key, n,
                   med(p, key, n), cm, mn(c, key, n), mx(c, key, n),
                   bm, mn(b, key, n), mx(b, key, n), cm - bm
        }
    }' "$raw" > "$out"
}

# ---------------------------------------------------------------------------

case "${1:-}" in
    up)    shift; cmd_up "$@" ;;
    down)  shift; cmd_down "$@" ;;
    build) shift; cmd_build "$@" ;;
    clean) shift; cmd_clean "$@" ;;
    run)   shift; cmd_run "$@" ;;
    *)
        sed -n '10,45p' "$0" | sed 's/^# \{0,1\}//'
        exit 2 ;;
esac
