/*
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2019-2020 Intel, Inc.  All rights reserved.
 * Copyright (c) 2019      Research Organization for Information Science
 *                         and Technology (RIST).  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef PRRTE_DL_LIBLTDL
#define PRRTE_DL_LIBLTDL

#include "prrte_config.h"

#include "src/mca/prtedl/prtedl.h"

#include <ltprtedl.h>


PRRTE_EXPORT extern prrte_prtedl_base_module_t prrte_prtedl_libltdl_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct prrte_dl_handle_t {
    lt_prtedlhandle ltprtedl_handle;
#if PRRTE_ENABLE_DEBUG
    char *filename;
#endif
};

typedef struct {
    prrte_prtedl_base_component_t base;

#if PRRTE_DL_LIBLTDL_HAVE_LT_DLADVISE
    /* If the version of libltdl that we are compiling against has
       lt_dladvise, use it to support opening DSOs in a variety of
       modes. */
    lt_dladvise advise_private_noext;
    lt_dladvise advise_private_ext;
    lt_dladvise advise_public_noext;
    lt_dladvise advise_public_ext;
#endif
} prrte_prtedl_libltdl_component_t;

PRRTE_EXPORT extern prrte_prtedl_libltdl_component_t prrte_prtedl_libltdl_component;

#endif /* PRRTE_DL_LIBLTDL */
