#
# Copyright (c) 2023-2025 Jeffrey M. Squyres.  All rights reserved.
# Copyright (c) 2023-2026 Nanook Consulting  All rights reserved.
#
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

# Install the prterun RST "source" files so that other projects can
# include them in their documentation, even if they do not have access
# to the PRTE source tree.
#
# Note that we install these files into the "data" directory (vs. the
# "doc" directory) so that packagers won't split these files into a
# "docs" sub-package that may not be installed when we build other
# packages that want to use these RST files.
rstdir = $(prtedatadir)/rst/prrte-rst-content
dist_rst_DATA = \
    cli-activate.rst \
    cli-add-host.rst \
    cli-add-hostfile.rst \
    cli-alloc-id.rst \
    cli-alloc-refid.rst \
    cli-allow-run-as-root.rst \
    cli-app-prefix.rst \
    cli-app.rst \
    cli-append-env.rst \
    cli-bind-to.rst \
    cli-continuous.rst \
    cli-dash-host.rst \
    cli-debug-daemons-file.rst \
    cli-debug-daemons.rst \
    cli-display.rst \
    cli-do-not-connect.rst \
    cli-dvm-hostfile.rst \
    cli-dvm-uri.rst \
    cli-dvm.rst \
    cli-enable-recovery.rst \
    cli-forward-signals.rst \
    cli-general.rst \
    cli-get-stack-traces.rst \
    cli-gpu-support.rst \
    cli-homo-nodes.rst \
    cli-launcher-hostfile.rst \
    cli-leave-session-attached.rst \
    cli-map-by.rst \
    cli-max-restarts.rst \
    cli-memory-alloc-kinds.rst \
    cli-namespace.rst \
    cli-no-aggregate-help.rst \
    cli-no-app-prefix.rst \
    cli-noprefix.rst \
    cli-notifications.rst \
    cli-np.rst \
    cli-npernode.rst \
    cli-num-connect-retries.rst \
    cli-output.rst \
    cli-path.rst \
    cli-personality.rst \
    cli-pid.rst \
    cli-pmix-prefix.rst \
    cli-pmixmca.rst \
    cli-prefix.rst \
    cli-preload-binary.rst \
    cli-preload-files.rst \
    cli-prepend-env.rst \
    cli-prtemca.rst \
    cli-pset.rst \
    cli-rank-by.rst \
    cli-report-pid.rst \
    cli-report-state-on-timeout.rst \
    cli-report-uri.rst \
    cli-runtime-options.rst \
    cli-session-id.rst \
    cli-set-cwd-to-session-dir.rst \
    cli-set-env.rst \
    cli-spawn-timeout.rst \
    cli-stdin.rst \
    cli-stop-in-app.rst \
    cli-stop-in-init.rst \
    cli-stop-on-exec.rst \
    cli-stream-buffering.rst \
    cli-system-server-first.rst \
    cli-system-server-only.rst \
    cli-timeout.rst \
    cli-tune.rst \
    cli-unset-env.rst \
    cli-wait-to-connect.rst \
    cli-wd.rst \
    cli-wdir.rst \
    cli-x.rst \
    cli-xterm.rst \
    definitions-pes.rst \
    definitions-slots.rst \
    deprecated-bind-to-core.rst \
    deprecated-display-allocation.rst \
    deprecated-display-devel-allocation.rst \
    deprecated-display-devel-map.rst \
    deprecated-display-map.rst \
    deprecated-display-topo.rst \
    deprecated-gmca.rst \
    deprecated-mca.rst \
    deprecated-merge-stderr-to-stdout.rst \
    deprecated-output-directory.rst \
    deprecated-output-filename.rst \
    deprecated-report-bindings.rst \
    deprecated-report-child-jobs-separately.rst \
    deprecated-show-progress.rst \
    deprecated-tag-output.rst \
    deprecated-timestamp-output.rst \
    deprecated-xml.rst \
    detail-directive-syntax.rst \
    detail-hostfiles.rst \
    detail-hosts-cli.rst \
    detail-hosts-relative-indexing.rst \
    detail-hosts-rm.rst \
    detail-placement.rst \
    detail-placement-examples.rst \
    detail-placement-rankfiles.rst \
    detail-placement-fundamentals.rst \
    detail-placement-deprecated.rst \
    detail-placement-diagnostics.rst \
    detail-placement-limits.rst
