.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pcc" "1" "" "2021-08-23" "PRRTE"
.hy
.SH NAME
.PP
pcc - Back-end PRTE wrapper command
.SH SYNOPSIS
.IP
.nf
\f[C]
pcc [options]
\f[R]
.fi
.SH DESCRIPTION
.PP
Compiler wrapper used to automatically insert compiler and linker flags
needed to compile PRTE applications.
.SH AUTHORS
.PP
The PRTE maintainers \[en] see https://github.com/openpmix/prte or the
file \f[C]AUTHORS\f[R].
.PP
This manual page was originally contributed by Dirk Eddelbuettel
<edd@debian.org>, one of the Debian GNU/Linux maintainers for Open MPI,
and may be used by others.
