.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "prte_info" "1" "" "2021-08-23" "PRRTE"
.hy
.SH NAME
.PP
prte_info - Display information about the PRTE installation
.SH SYNOPSIS
.IP
.nf
\f[C]
prte-info [options]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]prte_info\f[R] provides detailed information about the PRTE
installation.
It can be useful for at least three common scenarios:
.IP "1." 3
Checking local configuration and seeing how PRTE was installed.
.IP "2." 3
Submitting bug reports / help requests to the PRTE community (see
https://github.com/openpmix/prte/issues.
.IP "3." 3
Seeing a list of installed PRTE plugins and querying what MCA parameters
they support.
.SH OPTIONS
.PP
\f[C]prte_info\f[R] accepts the following options:
.TP
\f[B]\f[CB]-a|--all\f[B]\f[R]
Show all configuration options and MCA parameters
.TP
\f[B]\f[CB]--arch\f[B]\f[R]
Show architecture PRTE was compiled on
.TP
\f[B]\f[CB]-c|--config\f[B]\f[R]
Show configuration options
.TP
\f[B]\f[CB]-gmca|--gmca <param> <value>\f[B]\f[R]
Pass global MCA parameters that are applicable to all contexts.
.TP
\f[B]\f[CB]-h|--help\f[B]\f[R]
Shows help / usage message
.TP
\f[B]\f[CB]--hostname\f[B]\f[R]
Show the hostname on which PRTE was configured and built.
.TP
\f[B]\f[CB]--internal\f[B]\f[R]
Show internal MCA parameters (not meant to be modified by users)
.TP
\f[B]\f[CB]-mca|--mca <param> <value>\f[B]\f[R]
Pass context-specific MCA parameters; they are considered global if
\f[C]--gmca\f[R] is not used and only one context is specified.
.TP
\f[B]\f[CB]--param <type> <component>\f[B]\f[R]
Show MCA parameters.
The first parameter is the type of the component to display; the second
parameter is the specific component to display (or the keyword
\f[C]all\f[R], meaning \[lq]display all components of this type\[rq]).
.TP
\f[B]\f[CB]--parsable\f[B]\f[R]
When used in conjunction with other parameters, the output is \[ga]
displayed in a machine-parsable format
.TP
\f[B]\f[CB]--parseable\f[B]\f[R]
Synonym for \f[C]--parsable\f[R].
.TP
\f[B]\f[CB]--path <type>\f[B]\f[R]
Show paths that PRTE was configured with.
Accepts the following parameters: \f[C]prefix\f[R], \f[C]bindir\f[R],
\f[C]libdir\f[R], \f[C]incdir\f[R], \f[C]pkglibdir\f[R],
\f[C]sysconfdir\f[R].
.TP
\f[B]\f[CB]--pretty\f[B]\f[R]
When used in conjunction with other parameters, the output is displayed
in `prettyprint' format (default).
.TP
\f[B]\f[CB]-v|--version <component> <scope>\f[B]\f[R]
Show version of PRTE or a component.
can be the keywords \f[C]ompi\f[R] or \f[C]all\f[R], the name of a
framework (e.g., \f[C]coll\f[R] shows all components in the
\f[C]coll\f[R] framework), or the name of a specific component (e.g.,
\f[C]pls:rsh\f[R] shows the information from the rsh PLS component).
can be one of: \f[C]full\f[R], \f[C]major\f[R], \f[C]minor\f[R],
\f[C]release\f[R], \f[C]greek\f[R], \f[C]git\f[R].
.SH EXAMPLES
.TP
\f[B]\f[CB]prte_info\f[B]\f[R]
Show the default output of options and listing of installed components
in a human-readable / prettyprint format.
.TP
\f[B]\f[CB]prte_info --parsable\f[B]\f[R]
Show the default output of options and listing of installed components
in a machine-parsable format.
.TP
\f[B]\f[CB]prte_info --param rmcast udp\f[B]\f[R]
Show the MCA parameters of the \[lq]udp\[rq] RMCAST component in a
human-readable / prettyprint format.
.TP
\f[B]\f[CB]prte_info --param rmcast udp --parsable\f[B]\f[R]
Show the MCA parameters of the \[lq]udp\[rq] RMCAST component in a
machine-parsable format.
.TP
\f[B]\f[CB]prte_info --path bindir\f[B]\f[R]
Show the \[lq]bindir\[rq] that PRTE was configured with.
.TP
\f[B]\f[CB]prte_info --version prte full --parsable\f[B]\f[R]
Show the full version numbers of PRTE (including the PRTE version
number) in a machine-readable format.
.TP
\f[B]\f[CB]prte_info --version rmcast major\f[B]\f[R]
Show the major version number of all RMCAST components in a prettyprint
format.
.TP
\f[B]\f[CB]prte_info --version rmcast:tcp minor\f[B]\f[R]
Show the minor version number of the TCP RMCAST component in a
prettyprint format.
.TP
\f[B]\f[CB]prte_info --all\f[B]\f[R]
Show \f[C]all\f[R] information about the PRTE installation, including
all components that can be found, the MCA parameters that they support,
versions of PRTE and the components, etc.
.SH AUTHORS
.PP
The PRTE maintainers \[en] see https://github.com/openpmix/prte or the
file \f[C]AUTHORS\f[R].
.PP
This manual page was originally contributed by Dirk Eddelbuettel
<edd@debian.org>, one of the Debian GNU/Linux maintainers for Open MPI,
and may be used by others.
