.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "prted" "1" "" "2021-08-23" "PRRTE"
.hy
.SH NAME
.PP
prted - Start an PRTE User-Level Daemon
.SH SYNOPSIS
.IP
.nf
\f[C]
prted [options]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]prted\f[R] starts an PRTE daemon for the PRTE system.
.SH NOTE
.PP
The \f[C]prted\f[R] command is \f[I]not intended to be manually invoked
by end users.\f[R] It is part of the PRTE architecture and is invoked
automatically as necessary.
This man page is mainly intended for those adventerous end users and
system administrators who have noticed an \f[C]prted\f[R] process and
wondered what it is.
.PP
As such, the command line options accepted by the \f[C]prted\f[R] are
not listed below because they are considered internal and are therefore
subject to change between versions without warning.
Running \f[C]prted\f[R] with the \f[C]--help\f[R] command line option
will show all available options.
.SH AUTHORS
.PP
The PRTE maintainers \[en] see https://github.com/openpmix/prte or the
file \f[C]AUTHORS\f[R].
.PP
This manual page was originally contributed by Dirk Eddelbuettel
<edd@debian.org>, one of the Debian GNU/Linux maintainers for Open MPI,
and may be used by others.
