.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pterm" "1" "" "2021-08-23" "PRRTE"
.hy
.SH NAME
.PP
pterm - Terminate an instance of the PMIx Reference RTE (PRTE)
.SH SYNOPSIS
.IP
.nf
\f[C]
pterm JMS write some more here
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pterm\f[R] terminates an instance of the PMIx reference run time
environment (PRTE).
.PP
JMS write more here
.SH OPTIONS
.PP
JMS \f[C]pterm --help\f[R] shows this:
.IP
.nf
\f[C]
pterm (PRTE) 2.0.0a1

Usage: pterm [OPTION]...
Terminate an instance of the PMIx Reference RTE (PRTE)

/*****      General Options      *****/

-h|--help                            This help message
-v|--verbose                         Be verbose
-V|--version                         Print version and exit



/*****    DVM-Specific Options   *****/

   --dvm-uri <arg0>                  Specify the URI of the DVM master, or the name of the file (specified as
                                     file:filename) that contains that info
   --num-connect-retries             Max number of times to try to connect
   --pid <arg0>                      PID of the session-level daemon to which we should connect
   --system-server-first             First look for a system server and connect to it if found
   --system-server-only              Connect only to a system-level server
   --wait-to-connect                 Delay specified number of seconds before trying to connect
\f[R]
.fi
.SH AUTHORS
.PP
The PRTE maintainers \[en] see https://github.com/openpmix/prte or the
file \f[C]AUTHORS\f[R].
