/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */
#ifndef PRRTE_FRAMEWORKS_H
#define PRRTE_FRAMEWORKS_H

#include <src/mca/base/prrte_mca_base_framework.h>

extern prrte_mca_base_framework_t prrte_backtrace_base_framework;
extern prrte_mca_base_framework_t prrte_compress_base_framework;
extern prrte_mca_base_framework_t prrte_dl_base_framework;
extern prrte_mca_base_framework_t prrte_errmgr_base_framework;
extern prrte_mca_base_framework_t prrte_ess_base_framework;
extern prrte_mca_base_framework_t prrte_filem_base_framework;
extern prrte_mca_base_framework_t prrte_grpcomm_base_framework;
extern prrte_mca_base_framework_t prrte_if_base_framework;
extern prrte_mca_base_framework_t prrte_installdirs_base_framework;
extern prrte_mca_base_framework_t prrte_iof_base_framework;
extern prrte_mca_base_framework_t prrte_odls_base_framework;
extern prrte_mca_base_framework_t prrte_oob_base_framework;
extern prrte_mca_base_framework_t prrte_plm_base_framework;
extern prrte_mca_base_framework_t prrte_pstat_base_framework;
extern prrte_mca_base_framework_t prrte_ras_base_framework;
extern prrte_mca_base_framework_t prrte_rmaps_base_framework;
extern prrte_mca_base_framework_t prrte_rml_base_framework;
extern prrte_mca_base_framework_t prrte_routed_base_framework;
extern prrte_mca_base_framework_t prrte_rtc_base_framework;
extern prrte_mca_base_framework_t prrte_schizo_base_framework;
extern prrte_mca_base_framework_t prrte_state_base_framework;

static prrte_mca_base_framework_t *prrte_frameworks[] = {
    &prrte_backtrace_base_framework,
    &prrte_compress_base_framework,
    &prrte_dl_base_framework,
    &prrte_errmgr_base_framework,
    &prrte_ess_base_framework,
    &prrte_filem_base_framework,
    &prrte_grpcomm_base_framework,
    &prrte_if_base_framework,
    &prrte_installdirs_base_framework,
    &prrte_iof_base_framework,
    &prrte_odls_base_framework,
    &prrte_oob_base_framework,
    &prrte_plm_base_framework,
    &prrte_pstat_base_framework,
    &prrte_ras_base_framework,
    &prrte_rmaps_base_framework,
    &prrte_rml_base_framework,
    &prrte_routed_base_framework,
    &prrte_rtc_base_framework,
    &prrte_schizo_base_framework,
    &prrte_state_base_framework,
    NULL
};

#endif /* PRRTE_FRAMEWORKS_H */

