name: Build with PMIx v4.2

on: [pull_request]

jobs:
  ubuntu4:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends software-properties-common libhwloc-dev libevent-dev
    - name: Git clone OpenPMIx
      uses: actions/checkout@v3
      with:
            submodules: recursive
            repository: openpmix/openpmix
            path: openpmix/v4
            ref: v4.2
    - name: Build OpenPMIx
      run: |
        cd openpmix/v4
        ./autogen.pl
        ./configure --prefix=$RUNNER_TEMP/pmixinstall
        make -j
        make install
        cp examples/.libs/hello $RUNNER_TEMP/pmixinstall/bin
    - name: Git clone PRRTE
      uses: actions/checkout@v3
      with:
            submodules: recursive
            clean: false
    - name: Build PRRTE
      run: |
        ./autogen.pl
        ./configure --prefix=$RUNNER_TEMP/prteinstall --with-pmix=$RUNNER_TEMP/pmixinstall --enable-devel-check
        make -j
        make install
    - name: Tweak PRRTE
      run:  |
         # Tweak PRRTE
         mca_params="$HOME/.prte/mca-params.conf"
         mkdir -p "$(dirname "$mca_params")"
         echo rmaps_default_mapping_policy = :oversubscribe >> "$mca_params"
    - name: Run simple test
      run: |
         export PATH=$RUNNER_TEMP/prteinstall/bin:${PATH}
         export LD_LIBRARY_PATH=$RUNNER_TEMP/prteinstall/lib:${LD_LIBRARY_PATH}
         prterun -n 4 $RUNNER_TEMP/pmixinstall/bin/hello
      if:   ${{ true }}
      timeout-minutes: 5

  ubuntuClang4:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends software-properties-common libhwloc-dev libevent-dev clang
    - name: Git clone OpenPMIx
      uses: actions/checkout@v3
      with:
            submodules: recursive
            repository: openpmix/openpmix
            path: openpmix/v4
            ref: v4.2
    - name: Build OpenPMIx
      run: |
        cd openpmix/v4
        ./autogen.pl
        CC=clang ./configure --prefix=$RUNNER_TEMP/pmixinstall
        make -j
        make install
        cp examples/.libs/hello $RUNNER_TEMP/pmixinstall/bin
    - name: Git clone PRRTE
      uses: actions/checkout@v3
      with:
            submodules: recursive
            clean: false
    - name: Build PRRTE
      run: |
        ./autogen.pl

        pip3 install -r docs/requirements.txt
        CC=clang ./configure --prefix=$RUNNER_TEMP/prteinstall --with-pmix=$RUNNER_TEMP/pmixinstall $sphinx --enable-devel-check
        make -j
        make install
    - name: Tweak PRRTE
      run:  |
         # Tweak PRRTE
         mca_params="$HOME/.prte/mca-params.conf"
         mkdir -p "$(dirname "$mca_params")"
         echo rmaps_default_mapping_policy = :oversubscribe >> "$mca_params"
    - name: Run simple test
      run: |
         export PATH=$RUNNER_TEMP/prteinstall/bin:${PATH}
         export LD_LIBRARY_PATH=$RUNNER_TEMP/prteinstall/lib:${LD_LIBRARY_PATH}
         prterun -n 4 $RUNNER_TEMP/pmixinstall/bin/hello
      if:   ${{ true }}
      timeout-minutes: 5
