/*
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2019      Intel, Inc.  All rights reserved.
 * Copyright (c) 2019      Research Organization for Information Science
 *                         and Technology (RIST).  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef PRRTE_DL_DLOPEN
#define PRRTE_DL_DLOPEN

#include "prrte_config.h"

#include "src/mca/dl/dl.h"

PRRTE_EXPORT extern prrte_dl_base_module_t prrte_dl_dlopen_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct prrte_dl_handle_t {
    void *dlopen_handle;
#if PRRTE_ENABLE_DEBUG
    void *filename;
#endif
};

typedef struct {
    prrte_dl_base_component_t base;

    char *filename_suffixes_mca_storage;
    char **filename_suffixes;
} prrte_dl_dlopen_component_t;

PRRTE_EXPORT extern prrte_dl_dlopen_component_t prrte_dl_dlopen_component;

#endif /* PRRTE_DL_DLOPEN */
